improved configbuildtest files (also with container) and readme on versions

diff --git a/config_build_test b/config_build_test
--- a/config_build_test
+++ b/config_build_test
@@ -7,6 +7,12 @@ llvm_version="${2:-$REQUIRED}"
 [[ ${ifx_version} == "${REQUIRED}" ]] && echo "missing pos arg IFX_VERSION" && exit 1 
 [[ ${llvm_version} == "${REQUIRED}" ]] && echo "missing pos arg LLVM_VERSION" && exit 1 
 
+if [[ -z $(which spack) ]]
+then
+    echo "[ERROR]: spack not found. Spack is required for loading IFX and LLVM."
+    exit 1 
+fi
+
 (
 rm -rf build && mkdir build && cd build
 
diff --git a/container_depinstall_config_build_test b/container_depinstall_config_build_test
--- a/container_depinstall_config_build_test
+++ b/container_depinstall_config_build_test
@@ -4,7 +4,7 @@
 # ```
 # docker run -it -v $(pwd):/home/user/Enzyme enzyme-fortran
 # cd Enzyme
-# ./container_depinstall_config_build_test 15 2023.0.0
+# ./container_depinstall_config_build_test 2023.0.0 15
 # ```
 set -e
 
@@ -17,18 +17,18 @@ then
 fi
 
 required="required"
-matrix_llvm="${1:-$required}"
-matrix_ifx_version="${2:-$required}"
-
-if [[ ${matrix_llvm} == ${required} ]] 
-then
-    echo "[ERROR]: missing positional argument MATRIX_LLVM"
-    exit 1 
-fi
+matrix_ifx_version="${1:-$required}"
+matrix_llvm="${2:-$required}"
 
 if [[ ${matrix_ifx_version} == ${required} ]] 
 then
     echo "[ERROR]: missing positional argument MATRIX_IFX_VERSION"
+    exit 1 
+fi
+
+if [[ ${matrix_llvm} == ${required} ]] 
+then
+    echo "[ERROR]: missing positional argument MATRIX_LLVM"
     exit 1 
 fi
 
